[package]

name = "iomrascálaí"
version = "0.1.0"
authors = ["Urban Hafner <contact@urbanhafner.com>", "Thomas Poinsot <thomas.poinsot1@gmail.com>"]

[dependencies]

getopts         = "*"
regex           = "*"
regex_macros    = "*"
rustc-serialize = "*"
time            = "*"
